# Decap for Hugo using Hero Theme
backend:
  name: git-gateway
  branch: master
  publish_mode: editorial-workflow
  media_folder: "static/uploads"
  public_folder: "/uploads"

collections:
  - name: "blog"  # Used in route so /admin/collections/blog
    label: "Blog"  # Used in UI
    folder: "blog"
